
package com.helger.peppol.smlclient.participant;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.helger.commons.annotation.CodingStyleguideUnaware;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ManageBusinessIdentifierServiceSoap", targetNamespace = "http://busdox.org/serviceMetadata/ManageBusinessIdentifierService/1.0/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
@CodingStyleguideUnaware
public interface ManageBusinessIdentifierServiceSoap {


    /**
     * 
     * @param messagePart
     * @throws UnauthorizedFault
     * @throws NotFoundFault
     * @throws BadRequestFault
     * @throws InternalErrorFault
     */
    @WebMethod(operationName = "Create", action = "http://busdox.org/serviceMetadata/ManageBusinessIdentifierService/1.0/         :createIn")
    public void create(
        @WebParam(name = "CreateParticipantIdentifier", targetNamespace = "http://busdox.org/serviceMetadata/locator/1.0/", partName = "messagePart")
        ServiceMetadataPublisherServiceForParticipantType messagePart)
        throws BadRequestFault, InternalErrorFault, NotFoundFault, UnauthorizedFault
    ;

    /**
     * 
     * @param createListIn
     * @throws NotFoundFault
     * @throws UnauthorizedFault
     * @throws BadRequestFault
     * @throws InternalErrorFault
     */
    @WebMethod(operationName = "CreateList", action = "http://busdox.org/serviceMetadata/ManageBusinessIdentifierService/1.0/         :createListIn")
    public void createList(
        @WebParam(name = "CreateList", targetNamespace = "http://busdox.org/serviceMetadata/locator/1.0/", partName = "createListIn")
        ParticipantIdentifierPageType createListIn)
        throws BadRequestFault, InternalErrorFault, NotFoundFault, UnauthorizedFault
    ;

    /**
     * 
     * @param messagePart
     * @throws UnauthorizedFault
     * @throws NotFoundFault
     * @throws BadRequestFault
     * @throws InternalErrorFault
     */
    @WebMethod(operationName = "Delete", action = "http://busdox.org/serviceMetadata/ManageBusinessIdentifierService/1.0/         :deleteIn")
    public void delete(
        @WebParam(name = "DeleteParticipantIdentifier", targetNamespace = "http://busdox.org/serviceMetadata/locator/1.0/", partName = "messagePart")
        ServiceMetadataPublisherServiceForParticipantType messagePart)
        throws BadRequestFault, InternalErrorFault, NotFoundFault, UnauthorizedFault
    ;

    /**
     * 
     * @param deleteListIn
     * @throws NotFoundFault
     * @throws UnauthorizedFault
     * @throws BadRequestFault
     * @throws InternalErrorFault
     */
    @WebMethod(operationName = "DeleteList", action = "http://busdox.org/serviceMetadata/ManageBusinessIdentifierService/1.0/         :deleteListIn")
    public void deleteList(
        @WebParam(name = "DeleteList", targetNamespace = "http://busdox.org/serviceMetadata/locator/1.0/", partName = "deleteListIn")
        ParticipantIdentifierPageType deleteListIn)
        throws BadRequestFault, InternalErrorFault, NotFoundFault, UnauthorizedFault
    ;

    /**
     * 
     * @param messagePart
     * @return
     *     returns com.helger.peppol.smlclient.participant.ParticipantIdentifierPageType
     * @throws UnauthorizedFault
     * @throws NotFoundFault
     * @throws BadRequestFault
     * @throws InternalErrorFault
     */
    @WebMethod(operationName = "List", action = "http://busdox.org/serviceMetadata/ManageBusinessIdentifierService/1.0/         :listIn")
    @WebResult(name = "ParticipantIdentifierPage", targetNamespace = "http://busdox.org/serviceMetadata/locator/1.0/", partName = "messagePart")
    public ParticipantIdentifierPageType list(
        @WebParam(name = "PageRequest", targetNamespace = "http://busdox.org/serviceMetadata/locator/1.0/", partName = "messagePart")
        PageRequestType messagePart)
        throws BadRequestFault, InternalErrorFault, NotFoundFault, UnauthorizedFault
    ;

    /**
     * 
     * @param prepareMigrateIn
     * @throws NotFoundFault
     * @throws UnauthorizedFault
     * @throws BadRequestFault
     * @throws InternalErrorFault
     */
    @WebMethod(operationName = "PrepareToMigrate", action = "http://busdox.org/serviceMetadata/ManageBusinessIdentifierService/1.0/         :prepareMigrateIn")
    public void prepareToMigrate(
        @WebParam(name = "PrepareMigrationRecord", targetNamespace = "http://busdox.org/serviceMetadata/locator/1.0/", partName = "prepareMigrateIn")
        MigrationRecordType prepareMigrateIn)
        throws BadRequestFault, InternalErrorFault, NotFoundFault, UnauthorizedFault
    ;

    /**
     * 
     * @param migrateIn
     * @throws NotFoundFault
     * @throws UnauthorizedFault
     * @throws BadRequestFault
     * @throws InternalErrorFault
     */
    @WebMethod(operationName = "Migrate", action = "http://busdox.org/serviceMetadata/ManageBusinessIdentifierService/1.0/         :migrateIn")
    public void migrate(
        @WebParam(name = "CompleteMigrationRecord", targetNamespace = "http://busdox.org/serviceMetadata/locator/1.0/", partName = "migrateIn")
        MigrationRecordType migrateIn)
        throws BadRequestFault, InternalErrorFault, NotFoundFault, UnauthorizedFault
    ;

}
