
package com.helger.peppol.smlclient.participant;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import com.helger.commons.annotation.CodingStyleguideUnaware;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ManageBusinessIdentifierService", targetNamespace = "http://busdox.org/serviceMetadata/ManageBusinessIdentifierService/1.0/", wsdlLocation = "/WEB-INF/wsdl/ManageBusinessIdentifierService-1.0.wsdl")
@CodingStyleguideUnaware
public class ManageBusinessIdentifierService
    extends Service
{

    private final static URL MANAGEBUSINESSIDENTIFIERSERVICE_WSDL_LOCATION;
    private final static WebServiceException MANAGEBUSINESSIDENTIFIERSERVICE_EXCEPTION;
    private final static QName MANAGEBUSINESSIDENTIFIERSERVICE_QNAME = new QName("http://busdox.org/serviceMetadata/ManageBusinessIdentifierService/1.0/", "ManageBusinessIdentifierService");

    static {
        MANAGEBUSINESSIDENTIFIERSERVICE_WSDL_LOCATION = com.helger.peppol.smlclient.participant.ManageBusinessIdentifierService.class.getResource("/WEB-INF/wsdl/ManageBusinessIdentifierService-1.0.wsdl");
        WebServiceException e = null;
        if (MANAGEBUSINESSIDENTIFIERSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/WEB-INF/wsdl/ManageBusinessIdentifierService-1.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        MANAGEBUSINESSIDENTIFIERSERVICE_EXCEPTION = e;
    }

    public ManageBusinessIdentifierService() {
        super(__getWsdlLocation(), MANAGEBUSINESSIDENTIFIERSERVICE_QNAME);
    }

    public ManageBusinessIdentifierService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ManageBusinessIdentifierServiceSoap
     */
    @WebEndpoint(name = "ManageBusinessIdentifierServicePort")
    public ManageBusinessIdentifierServiceSoap getManageBusinessIdentifierServicePort() {
        return super.getPort(new QName("http://busdox.org/serviceMetadata/ManageBusinessIdentifierService/1.0/", "ManageBusinessIdentifierServicePort"), ManageBusinessIdentifierServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManageBusinessIdentifierServiceSoap
     */
    @WebEndpoint(name = "ManageBusinessIdentifierServicePort")
    public ManageBusinessIdentifierServiceSoap getManageBusinessIdentifierServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://busdox.org/serviceMetadata/ManageBusinessIdentifierService/1.0/", "ManageBusinessIdentifierServicePort"), ManageBusinessIdentifierServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANAGEBUSINESSIDENTIFIERSERVICE_EXCEPTION!= null) {
            throw MANAGEBUSINESSIDENTIFIERSERVICE_EXCEPTION;
        }
        return MANAGEBUSINESSIDENTIFIERSERVICE_WSDL_LOCATION;
    }

}
