
package com.helger.peppol.smlclient.bdmslcipa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.helger.commons.annotation.CodingStyleguideUnaware;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BDMSLCipaServiceSoap", targetNamespace = "ec:services:wsdl:BDMSL:1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
@CodingStyleguideUnaware
public interface BDMSLCipaServiceSoap {


    /**
     * 
     * @param messagePart
     * @throws UnauthorizedFault
     * @throws NotFoundFault
     * @throws BadRequestFault
     * @throws InternalErrorFault
     */
    @WebMethod(operationName = "PrepareChangeCertificate", action = "ec:services:wsdl:BDMSL:1.0:prepareChangeCertificateIn")
    public void prepareChangeCertificate(
        @WebParam(name = "PrepareChangeCertificate", targetNamespace = "ec:services:wsdl:BDMSL:data:1.0", partName = "messagePart")
        PrepareChangeCertificateType messagePart)
        throws BadRequestFault, InternalErrorFault, NotFoundFault, UnauthorizedFault
    ;

    /**
     * 
     * @param messagePart
     * @throws UnauthorizedFault
     * @throws NotFoundFault
     * @throws BadRequestFault
     * @throws InternalErrorFault
     */
    @WebMethod(operationName = "CreateParticipantIdentifier", action = "ec:services:wsdl:BDMSL:1.0:createParticipantIdentifierIn")
    public void createParticipantIdentifier(
        @WebParam(name = "SMPAdvancedServiceForParticipantService", targetNamespace = "ec:services:wsdl:BDMSL:data:1.0", partName = "messagePart")
        SMPAdvancedServiceForParticipantType messagePart)
        throws BadRequestFault, InternalErrorFault, NotFoundFault, UnauthorizedFault
    ;

    /**
     * 
     * @param messagePart
     * @return
     *     returns com.helger.peppol.smlclient.bdmslcipa.ListParticipantsType
     * @throws UnauthorizedFault
     * @throws InternalErrorFault
     */
    @WebMethod(operationName = "ListParticipants", action = "ec:services:wsdl:BDMSL:1.0:listParticipantsIn")
    @WebResult(name = "ListParticipantsOut", targetNamespace = "ec:services:wsdl:BDMSL:data:1.0", partName = "messagePart")
    public ListParticipantsType listParticipants(
        @WebParam(name = "ListParticipantsIn", targetNamespace = "ec:services:wsdl:BDMSL:data:1.0", partName = "messagePart")
        ListParticipantsInType messagePart)
        throws InternalErrorFault, UnauthorizedFault
    ;

    /**
     * 
     * @param messagePart
     */
    @WebMethod(operationName = "IsAlive", action = "ec:services:wsdl:BDMSL:1.0:isAliveIn")
    public void isAlive(
        @WebParam(name = "IsAlive", targetNamespace = "ec:services:wsdl:BDMSL:data:1.0", partName = "messagePart")
        IsAliveType messagePart);

    /**
     * 
     * @param messagePart
     * @throws InternalErrorFault
     */
    @WebMethod(operationName = "ClearCache", action = "ec:services:wsdl:BDMSL:1.0:clearCacheIn")
    public void clearCache(
        @WebParam(name = "ClearCache", targetNamespace = "ec:services:wsdl:BDMSL:data:1.0", partName = "messagePart")
        ClearCacheType messagePart)
        throws InternalErrorFault
    ;

}
