
package com.helger.peppol.smlclient.smp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.helger.commons.annotation.CodingStyleguideUnaware;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ManageServiceMetadataServiceSoap", targetNamespace = "http://busdox.org/serviceMetadata/ManageServiceMetadataService/1.0/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
@CodingStyleguideUnaware
public interface ManageServiceMetadataServiceSoap {


    /**
     * 
     * @param messagePart
     * @throws BadRequestFault
     * @throws UnauthorizedFault
     * @throws InternalErrorFault
     */
    @WebMethod(operationName = "Create", action = "http://busdox.org/serviceMetadata/ManageServiceMetadataService/1.0/:createIn")
    public void create(
        @WebParam(name = "CreateServiceMetadataPublisherService", targetNamespace = "http://busdox.org/serviceMetadata/locator/1.0/", partName = "messagePart")
        ServiceMetadataPublisherServiceType messagePart)
        throws BadRequestFault, InternalErrorFault, UnauthorizedFault
    ;

    /**
     * 
     * @param messagePart
     * @return
     *     returns com.helger.peppol.smlclient.smp.ServiceMetadataPublisherServiceType
     * @throws BadRequestFault
     * @throws NotFoundFault
     * @throws UnauthorizedFault
     * @throws InternalErrorFault
     */
    @WebMethod(operationName = "Read", action = "http://busdox.org/serviceMetadata/ManageServiceMetadataService/1.0/:readIn")
    @WebResult(name = "ServiceMetadataPublisherService", targetNamespace = "http://busdox.org/serviceMetadata/locator/1.0/", partName = "messagePart")
    public ServiceMetadataPublisherServiceType read(
        @WebParam(name = "ReadServiceMetadataPublisherService", targetNamespace = "http://busdox.org/serviceMetadata/locator/1.0/", partName = "messagePart")
        ServiceMetadataPublisherServiceType messagePart)
        throws BadRequestFault, InternalErrorFault, NotFoundFault, UnauthorizedFault
    ;

    /**
     * 
     * @param messagePart
     * @throws BadRequestFault
     * @throws NotFoundFault
     * @throws UnauthorizedFault
     * @throws InternalErrorFault
     */
    @WebMethod(operationName = "Update", action = "http://busdox.org/serviceMetadata/ManageServiceMetadataService/1.0/:updateIn")
    public void update(
        @WebParam(name = "UpdateServiceMetadataPublisherService", targetNamespace = "http://busdox.org/serviceMetadata/locator/1.0/", partName = "messagePart")
        ServiceMetadataPublisherServiceType messagePart)
        throws BadRequestFault, InternalErrorFault, NotFoundFault, UnauthorizedFault
    ;

    /**
     * 
     * @param messagePart
     * @throws BadRequestFault
     * @throws NotFoundFault
     * @throws UnauthorizedFault
     * @throws InternalErrorFault
     */
    @WebMethod(operationName = "Delete", action = "http://busdox.org/serviceMetadata/ManageServiceMetadataService/1.0/:deleteIn")
    public void delete(
        @WebParam(name = "ServiceMetadataPublisherID", targetNamespace = "http://busdox.org/serviceMetadata/locator/1.0/", partName = "messagePart")
        String messagePart)
        throws BadRequestFault, InternalErrorFault, NotFoundFault, UnauthorizedFault
    ;

}
