
package com.helger.peppol.smlclient.smp;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import com.helger.commons.annotation.CodingStyleguideUnaware;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ManageServiceMetadataService", targetNamespace = "http://busdox.org/serviceMetadata/ManageServiceMetadataService/1.0/", wsdlLocation = "/WEB-INF/wsdl/ManageServiceMetadataService-1.0.wsdl")
@CodingStyleguideUnaware
public class ManageServiceMetadataService
    extends Service
{

    private final static URL MANAGESERVICEMETADATASERVICE_WSDL_LOCATION;
    private final static WebServiceException MANAGESERVICEMETADATASERVICE_EXCEPTION;
    private final static QName MANAGESERVICEMETADATASERVICE_QNAME = new QName("http://busdox.org/serviceMetadata/ManageServiceMetadataService/1.0/", "ManageServiceMetadataService");

    static {
        MANAGESERVICEMETADATASERVICE_WSDL_LOCATION = com.helger.peppol.smlclient.smp.ManageServiceMetadataService.class.getResource("/WEB-INF/wsdl/ManageServiceMetadataService-1.0.wsdl");
        WebServiceException e = null;
        if (MANAGESERVICEMETADATASERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/WEB-INF/wsdl/ManageServiceMetadataService-1.0.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        MANAGESERVICEMETADATASERVICE_EXCEPTION = e;
    }

    public ManageServiceMetadataService() {
        super(__getWsdlLocation(), MANAGESERVICEMETADATASERVICE_QNAME);
    }

    public ManageServiceMetadataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ManageServiceMetadataServiceSoap
     */
    @WebEndpoint(name = "ManageServiceMetadataServicePort")
    public ManageServiceMetadataServiceSoap getManageServiceMetadataServicePort() {
        return super.getPort(new QName("http://busdox.org/serviceMetadata/ManageServiceMetadataService/1.0/", "ManageServiceMetadataServicePort"), ManageServiceMetadataServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManageServiceMetadataServiceSoap
     */
    @WebEndpoint(name = "ManageServiceMetadataServicePort")
    public ManageServiceMetadataServiceSoap getManageServiceMetadataServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://busdox.org/serviceMetadata/ManageServiceMetadataService/1.0/", "ManageServiceMetadataServicePort"), ManageServiceMetadataServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANAGESERVICEMETADATASERVICE_EXCEPTION!= null) {
            throw MANAGESERVICEMETADATASERVICE_EXCEPTION;
        }
        return MANAGESERVICEMETADATASERVICE_WSDL_LOCATION;
    }

}
